### ISSUE TITLE
Initial plugin release

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-gradle-plugin#1]
The plugin provides a single task which injects the [AppMap agent](https://github.com/applandinc/appmap-java) into the JDK. It also takes some optional configuration variables. It should not be executed by default. It must be executed explicitly, either via specifying the task in the command line (`./gradlew appmap test`) or by changing another task to depend on `appmap`.

An example plugin declaration within `gradle.build`:
```groovy
plugins {
    id "com.appland.appmap" version "0.5.3"
}

// declare AppMap configuration
appmap {
  configFile 'appmap.yml'
  outputDirectory 'build/appmap'
  debug false
  eventValueSize 1024
}
```

**Comment by marcuss** [comment]
@dustinbyrne 
Could the configuration file look like:

```
appmap {
    configFile = file("$projectDir/appmap2.yml")
    outputDirectory = file("$projectDir/target/appmap2")
    skip = true
    debug = "info"
    debugFile = "target/appmap/agent2.log"
    eventValueSize = 1024
}
```

**Comment by dustinbyrne** [comment]
Yes, let's maintain familiar conventions. The default paths we choose should also remain consistent with Gradle (e.g. `build/appmap` over `target/appmap`).

**Comment by marcuss** [comment]
I think this one can be close as: https://github.com/applandinc/appmap-gradle-plugin/pull/2#event-4599973293
is merged already.
